spring:
  datasource:
    carp:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/flinkful?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:123456}