server:
  port: 8893
  tomcat.uri-encoding: UTF-8
  servlet.context-path: /${spring.application.name}

spring:
  application.name: flinkful-rest
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  mvc.pathmatch.matching-strategy: ant_path_matcher
  servlet.multipart:
    enabled: true
    max-file-size: 1024MB
    max-request-size: 1024MB

management:
  endpoints.web.exposure.include: "*"

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  default-flat-param-object: true
knife4j:
  enable: true
  production: false
  setting:
    language: zh_cn
    enable-footer: true
    enable-debug: true
    enable-open-api: true
    enable-host: false
    enable-dynamic-parameter: true
    enable-version: true
  basic.enable: false
  cors: true