# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release-Image

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      jdk:
        required: true
        type: string
      image:
        required: true
        type: string
      registry:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      HUB_USERNAME:
        required: true
      HUB_PASSWORD:
        required: true

jobs:
  release:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up JDK ${{ inputs.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.jdk }}
          distribution: temurin
          cache: maven
      - name: Setup Version
        run: |
            VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.registry }}/${{ inputs.repository }}/${{ inputs.image }}
          tags: |
            type=semver,event=tag,pattern={{version}}
            type=semver,event=tag,pattern={{major}}.{{minor}}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.HUB_PASSWORD }}
          password: ${{ secrets.HUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Compile
        run: ./mvnw -e -B -U -T 4C clean -Dfast -DskipTests
      - name: Build Image
        id: build
        uses: docker/build-push-action@v5
        with:
          no-cache: false
          cache-from: type=gha
          cache-to: type=gha
          push: false
          context: .
          platforms: linux/amd64,linux/arm64
          file: tools/docker/build/${{ inputs.image }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}